version: '2'
services:
  buildbot:
    image: buildbot/buildbot-master:master
    env_file:
        - db.env
    environment:
        - BUILDBOT_CONFIG_DIR=config
        - BUILDBOT_CONFIG_URL=https://github.com/chigraph/buildbot/archive/master.tar.gz
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9989:9989"
